modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="thevoid"
version="0.2.5"
displayName="The void"
authors="kel'hazz"
description='''NOW, HEAR THE SLIENCE OF ANNIHILATION!'''

[[dependencies.thevoid]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.thevoid]]
    modId="minecraft"
    mandatory=true

    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


